// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web.Data;

#nullable disable

namespace web.Migrations
{
    [DbContext(typeof(TrgovinaContext))]
    [Migration("20221219140608_Test")]
    partial class Test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("web.Models.Izdelek", b =>
                {
                    b.Property<int>("IzdelekID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IzdelekID"), 1L, 1);

                    b.Property<double>("IzdelekCena")
                        .HasColumnType("float");

                    b.Property<string>("IzdelekIme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IzdelekVrsta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KmetijaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RokNakupa")
                        .HasColumnType("datetime2");

                    b.HasKey("IzdelekID");

                    b.HasIndex("KmetijaID");

                    b.ToTable("Izdelek", (string)null);
                });

            modelBuilder.Entity("web.Models.Kmetija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Lastnik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokacija")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kmetija", (string)null);
                });

            modelBuilder.Entity("web.Models.Izdelek", b =>
                {
                    b.HasOne("web.Models.Kmetija", "Kmetija")
                        .WithMany("Izdelki")
                        .HasForeignKey("KmetijaID");

                    b.Navigation("Kmetija");
                });

            modelBuilder.Entity("web.Models.Kmetija", b =>
                {
                    b.Navigation("Izdelki");
                });
#pragma warning restore 612, 618
        }
    }
}
